name: Production Tag Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.EXPLORER_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.EXPLORER_VERCEL_PROJECT_ID }}

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Push events to every tag with 3 version numbers, e.g. v1.0.13

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run:
          vercel pull --yes --environment=production --token=${{
          secrets.JACK_BASTION_VERCEL_ACCESS_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.JACK_BASTION_VERCEL_ACCESS_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.JACK_BASTION_VERCEL_ACCESS_TOKEN }}
