name: Alias dev domain

env:
  VERCEL_ORG_ID: ${{secrets.JACKHKMATTHEWS_VERCEL_TEAM_ID}}
  VERCEL_PROJECT_ID: ${{secrets.JACKHKMATTHEWS_PERSONAL_WEBSITE_VERCEL_PROJECT_ID}}

on:
  workflow_dispatch:
    inputs:
      domain:
        description: Choose a domain to alias
        required: false
        default: dev1
        type: choice
        options:
          - dev1
          - dev2

jobs:
  alias-dev-domain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set domain to branch
        run: |
          DOMAIN="${{ github.event.inputs.domain }}.jackhkmatthews.com"
          URL="https://api.vercel.com/v9/projects/${{secrets.JACKHKMATTHEWS_PERSONAL_WEBSITE_VERCEL_PROJECT_ID}}/domains/${DOMAIN}?slug=jackhkmatthews-projects&teamId=${{secrets.JACKHKMATTHEWS_VERCEL_TEAM_ID}}"
          echo "Setting domain ${DOMAIN} to branch ${{ github.ref_name }}"
          curl -X PATCH "$URL" \
            -H "Authorization: Bearer ${{secrets.JACKHKMATTHEWS_VERCEL_ACCESS_TOKEN}}" \
            -H "Content-Type: application/json" \
            -d '{
              "gitBranch": "${{ github.ref_name }}"
            }'
