name: Alias dev domain

env:
  VERCEL_ORG_ID: ${{secrets.JACKHKMATTHEWS_VERCEL_TEAM_ID}}
  VERCEL_PROJECT_ID: ${{secrets.JACKHKMATTHEWS_PERSONAL_WEBSITE_VERCEL_PROJECT_ID}}

on:
  workflow_dispatch:
    inputs:
      domain:
        description: Choose a domain to alias
        required: false
        default: dev1
        type: choice
        options:
          - dev1
          - dev2

jobs:
  alias-dev-domain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
          cache: "pnpm"

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Build preview and alias with Vercel
        run: |
          url=$(vercel deploy \
            --scope=${{secrets.JACKHKMATTHEWS_VERCEL_TEAM_ID}} \
            --token=${{secrets.JACKHKMATTHEWS_VERCEL_ACCESS_TOKEN}}); \
          vercel alias "$url" ${{github.event.inputs.domain}}.jackhkmatthews.com \
            --scope=${{secrets.JACKHKMATTHEWS_VERCEL_TEAM_ID}} \
            --token=${{secrets.JACKHKMATTHEWS_VERCEL_ACCESS_TOKEN}}
