name: Tag production deployment

env:
  VERCEL_ORG_ID: ${{secrets.JACKHKMATTHEWS_VERCEL_TEAM_ID}}
  VERCEL_PROJECT_ID: ${{secrets.JACKHKMATTHEWS_PERSONAL_WEBSITE_VERCEL_PROJECT_ID}}

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Push events to every tag with 3 version numbers, e.g. v1.0.13

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
          cache: "pnpm"

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Promote staging on Vercel to production
        run: |
          vercel promote https://staging.jackhkmatthews.com \
            --scope=${{secrets.JACKHKMATTHEWS_VERCEL_TEAM_ID}} \
            --token=${{secrets.JACKHKMATTHEWS_VERCEL_ACCESS_TOKEN}}
